version: '3'
services:
 docker:
    image: docker-angular1
    container_name: docker-angular1
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    command: ['npm', 'run', 'start']
    ports:
      - "8080:8080"


